# fly.toml app configuration file generated for c8000elo on 2024-09-05T22:17:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'c8000elo'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  HOSTNAME = "0.0.0.0"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
